"""CrewBoardStore — SQLite-backed CRUD for the kanban.

Thin layer over the schema in `gateway.crew_board.schema`. Lives in
the same DB as the vault index (`.vault-writer/vault.db`) but never
touches the notes / FTS / vec tables. Audit log entries are written
on every state-mutating call so the trail is automatic.

Sync API. Callers in async paths should wrap in `asyncio.to_thread`
when on a hot path; SQLite is fast enough that for the typical
board operation (a handful of rows) this is overkill.
"""

from __future__ import annotations

import json
import sqlite3
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable

from gateway.crew_board import schema


@dataclass
class Board:
    board_id: str
    name: str
    description: str
    created_at: str = ""


@dataclass
class Project:
    slug: str
    path: str
    name: str
    enabled: bool = False
    push_allowed: bool = False
    test_cmd: str | None = None
    created_at: str = ""
    updated_at: str = ""
    # Real "last worked on" timestamp (ISO-8601 UTC) = max(git HEAD commit
    # time, dir mtime), set by the scanner. Use this for recency sorting,
    # NOT updated_at (which is just the last DB upsert / scan time).
    modified_at: str | None = None
    # Opt-in: run each task in its own git worktree and allow >1
    # concurrent task for the assignee (capped by lane count). Default
    # off — the bench-proven model needs both GPUs so single-lane stays
    # the safe default.
    parallel: bool = False


@dataclass
class Task:
    slug: str
    title: str
    body: str = ""
    status: str = schema.STATUS_PROPOSED
    project_slug: str = ""
    assignee: str = "none"
    created_by: str = "owner"
    priority: str = "medium"
    estimate: str | None = None
    acceptance_criteria: list[dict] = field(default_factory=list)
    files_of_interest: list[str] = field(default_factory=list)
    depends_on: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    attempt_count: int = 0
    last_branch: str | None = None
    last_pr_url: str | None = None
    verify_results: dict = field(default_factory=dict)
    created_at: str = ""
    updated_at: str = ""
    # Optional reviewer that must approve a task before it can leave
    # REVIEW → DONE. When None, REVIEW waits for the owner.
    review_by: str | None = None
    # When >2, the hive_agent_loop holds off on auto-done until this
    # many consecutive green pytest runs have happened. Lets polish
    # tasks iterate instead of exiting at first green.
    polish_iters: int | None = None
    # Optional shell command run by the verifier AFTER pytest passes,
    # in the project dir. Non-zero exit fails the tier. Used as the
    # integration smoke gate.
    smoke_cmd: str | None = None
    # Token usage tracked SEPARATELY — never combined. hive = Ollama
    # eval tokens, claude = Claude CLI tokens.
    hive_tokens: int = 0
    claude_tokens: int = 0
    # Last heartbeat from an active runner (ISO/UTC). The reaper uses
    # this to distinguish a live long-running task from a crash-orphan.
    heartbeat_at: str | None = None
    # Agent-turn telemetry (hive loop): total turns + unparseable replies.
    # Powers the stats parse-fail rate via a cheap SUM.
    agent_turns: int = 0
    parse_fails: int = 0
    # Live current action ("turn N · tool target") — what the agent is
    # doing right now, surfaced on the board for live watching.
    last_action: str | None = None
    # Content requests. kind='content' tasks are generated by the Image/Video
    # shims, not a code runner. content_spec holds the request + result media.
    kind: str = "code"
    content_spec: dict = field(default_factory=dict)
    # P6 goal-completion loop: the goal_id this task belongs to (None for
    # tasks not created as part of a /board/decompose goal plan).
    goal_id: str | None = None
    # P2 v-Next: which board this task belongs to. 'default' for all existing
    # tasks (back-compat via ALTER TABLE DEFAULT in schema migrations).
    board_id: str = "default"
    # #198: last-agent handoff summary — "what I did + current state + next
    # step" — plus who wrote it (model/agent) and when. Overwritten on each
    # agent touch so it always reflects the most recent worker.
    last_summary: str | None = None
    last_summary_by: str | None = None
    last_summary_at: str | None = None
    # CP1: live agent reasoning stream + a pending owner steer nudge.
    live_thoughts: list = field(default_factory=list)
    steer_message: str | None = None
    # CP2: master-plan spec (kind='plan' tickets awaiting approval in proposed).
    plan_spec: dict = field(default_factory=dict)


@dataclass
class Lesson:
    project_slug: str
    body: str
    task_slug: str = ""
    tags: list[str] = field(default_factory=list)
    created_at: str = ""


@dataclass
class AuditEntry:
    task_slug: str
    actor: str
    action: str
    detail: str = ""
    metadata: dict = field(default_factory=dict)
    created_at: str = ""


class CrewBoardStore:
    def __init__(self, db_path: Path) -> None:
        self._db_path = Path(db_path)
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        # check_same_thread=False so the gateway's worker threads can
        # share. We serialize ourselves via a single connection +
        # short transactions; SQLite's own locking handles the rest.
        self._conn = sqlite3.connect(
            self._db_path, timeout=5.0, check_same_thread=False,
        )
        self._conn.row_factory = sqlite3.Row
        # WAL mode allows a second writer process (vault_writer) to
        # coexist without SQLITE_BUSY errors. busy_timeout backs off
        # gracefully if a lock is held briefly.
        self._conn.execute("PRAGMA journal_mode=WAL")
        self._conn.execute("PRAGMA busy_timeout=5000")
        # Serialise all execute/commit calls so the store is genuinely
        # thread-safe even if a future code path calls it from a worker
        # thread (currently only the event-loop thread touches it, but
        # the lock is cheap insurance). RLock so internal helpers
        # (_audit, _next_task_slug) can be called from within an
        # already-locked public method without deadlocking.
        self._lock = threading.RLock()
        schema.apply(self._conn)

    def close(self) -> None:
        self._conn.close()

    # ---------------------------------------------------------------- helpers

    def _row_to_project(self, row: sqlite3.Row) -> Project:
        return Project(
            slug=row["slug"],
            path=row["path"],
            name=row["name"],
            enabled=bool(row["enabled"]),
            push_allowed=bool(row["push_allowed"]),
            test_cmd=row["test_cmd"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            modified_at=(
                row["modified_at"] if "modified_at" in row.keys() else None
            ),
            parallel=bool(
                row["parallel"] if "parallel" in row.keys() else 0
            ),
        )

    def _row_to_task(self, row: sqlite3.Row) -> Task:
        return Task(
            slug=row["slug"],
            title=row["title"],
            body=row["body"],
            status=row["status"],
            project_slug=row["project_slug"],
            assignee=row["assignee"],
            created_by=row["created_by"],
            priority=row["priority"],
            estimate=row["estimate"],
            acceptance_criteria=json.loads(row["acceptance_criteria"]),
            files_of_interest=json.loads(row["files_of_interest"]),
            depends_on=json.loads(row["depends_on"]),
            tags=json.loads(row["tags"]),
            attempt_count=row["attempt_count"],
            last_branch=row["last_branch"],
            last_pr_url=row["last_pr_url"],
            verify_results=json.loads(row["verify_results"]),
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            review_by=(
                row["review_by"] if "review_by" in row.keys() else None
            ),
            polish_iters=(
                row["polish_iters"] if "polish_iters" in row.keys() else None
            ),
            smoke_cmd=(
                row["smoke_cmd"] if "smoke_cmd" in row.keys() else None
            ),
            hive_tokens=(
                row["hive_tokens"] if "hive_tokens" in row.keys() else 0
            ) or 0,
            claude_tokens=(
                row["claude_tokens"] if "claude_tokens" in row.keys() else 0
            ) or 0,
            heartbeat_at=(
                row["heartbeat_at"] if "heartbeat_at" in row.keys() else None
            ),
            agent_turns=(
                row["agent_turns"] if "agent_turns" in row.keys() else 0
            ) or 0,
            parse_fails=(
                row["parse_fails"] if "parse_fails" in row.keys() else 0
            ) or 0,
            last_action=(
                row["last_action"] if "last_action" in row.keys() else None
            ),
            kind=(
                row["kind"] if "kind" in row.keys() and row["kind"] else "code"
            ),
            content_spec=(
                json.loads(row["content_spec"])
                if "content_spec" in row.keys() and row["content_spec"]
                else {}
            ),
            goal_id=(
                row["goal_id"] if "goal_id" in row.keys() else None
            ),
            board_id=(
                row["board_id"] if "board_id" in row.keys() and row["board_id"]
                else "default"
            ),
            last_summary=(
                row["last_summary"] if "last_summary" in row.keys() else None
            ),
            last_summary_by=(
                row["last_summary_by"] if "last_summary_by" in row.keys() else None
            ),
            last_summary_at=(
                row["last_summary_at"] if "last_summary_at" in row.keys() else None
            ),
            live_thoughts=(
                json.loads(row["live_thoughts"])
                if "live_thoughts" in row.keys() and row["live_thoughts"]
                else []
            ),
            steer_message=(
                row["steer_message"] if "steer_message" in row.keys() else None
            ),
            plan_spec=(
                json.loads(row["plan_spec"])
                if "plan_spec" in row.keys() and row["plan_spec"]
                else {}
            ),
        )

    def _row_to_audit(self, row: sqlite3.Row) -> AuditEntry:
        return AuditEntry(
            task_slug=row["task_slug"],
            actor=row["actor"],
            action=row["action"],
            detail=row["detail"],
            metadata=json.loads(row["metadata"]),
            created_at=row["created_at"],
        )

    def _next_task_slug(self) -> str:
        # Called from within an already-locked public method (RLock is reentrant).
        row = self._conn.execute(
            "SELECT next_n FROM crew_task_counter WHERE scope = 'task'"
        ).fetchone()
        n = int(row["next_n"]) if row else 1
        self._conn.execute(
            "UPDATE crew_task_counter SET next_n = ? WHERE scope = 'task'",
            (n + 1,),
        )
        return f"T-{n:04d}"

    def _audit(
        self, task_slug: str, actor: str, action: str,
        detail: str = "", metadata: dict | None = None,
    ) -> None:
        # Called from within an already-locked public method (RLock is reentrant).
        self._conn.execute(
            """
            INSERT INTO crew_audit
                (task_slug, actor, action, detail, metadata)
            VALUES (?, ?, ?, ?, ?)
            """,
            (
                task_slug, actor, action, detail,
                json.dumps(metadata or {}, separators=(",", ":")),
            ),
        )

    # ---------------------------------------------------------------- projects

    def upsert_project(self, p: Project) -> Project:
        with self._lock:
            existing = self._conn.execute(
                "SELECT slug FROM crew_projects WHERE slug = ?",
                (p.slug,),
            ).fetchone()
            if existing:
                self._conn.execute(
                    """
                    UPDATE crew_projects
                    SET path = ?, name = ?, test_cmd = ?, parallel = ?,
                        modified_at = COALESCE(?, modified_at),
                        updated_at = datetime('now')
                    WHERE slug = ?
                    """,
                    (
                        p.path, p.name, p.test_cmd, int(p.parallel),
                        p.modified_at, p.slug,
                    ),
                )
            else:
                self._conn.execute(
                    """
                    INSERT INTO crew_projects
                        (slug, path, name, enabled, push_allowed, test_cmd,
                         parallel, modified_at)
                    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        p.slug, p.path, p.name,
                        int(p.enabled), int(p.push_allowed), p.test_cmd,
                        int(p.parallel), p.modified_at,
                    ),
                )
            self._conn.commit()
            return self.get_project(p.slug)  # type: ignore[return-value]

    def get_project(self, slug: str) -> Project | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM crew_projects WHERE slug = ?", (slug,),
            ).fetchone()
            return self._row_to_project(row) if row else None

    def list_projects(self, *, enabled_only: bool = False) -> list[Project]:
        with self._lock:
            if enabled_only:
                rows = self._conn.execute(
                    "SELECT * FROM crew_projects WHERE enabled = 1 ORDER BY slug"
                ).fetchall()
            else:
                rows = self._conn.execute(
                    "SELECT * FROM crew_projects ORDER BY slug"
                ).fetchall()
            return [self._row_to_project(r) for r in rows]

    def delete_project(self, slug: str) -> bool:
        """Delete a project row by slug. Returns True if a row was removed.

        Does NOT touch tasks — callers must ensure the project is empty (or
        intentionally orphan its tasks) first.
        """
        with self._lock:
            cur = self._conn.execute(
                "DELETE FROM crew_projects WHERE slug = ?", (slug,),
            )
            self._conn.commit()
            return cur.rowcount > 0

    def set_project_enabled(self, slug: str, *, enabled: bool) -> None:
        with self._lock:
            self._conn.execute(
                "UPDATE crew_projects SET enabled = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (int(enabled), slug),
            )
            self._conn.commit()

    def set_project_push_allowed(self, slug: str, *, allowed: bool) -> None:
        with self._lock:
            self._conn.execute(
                "UPDATE crew_projects SET push_allowed = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (int(allowed), slug),
            )
            self._conn.commit()

    def set_project_parallel(self, slug: str, *, parallel: bool) -> None:
        """Toggle worktree-per-task parallel lanes for a project."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_projects SET parallel = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (int(parallel), slug),
            )
            self._conn.commit()

    # ---------------------------------------------------------------- tasks

    def create_task(
        self, *,
        title: str,
        project_slug: str,
        body: str = "",
        created_by: str = "owner",
        priority: str = "medium",
        estimate: str | None = None,
        acceptance_criteria: list[dict] | None = None,
        files_of_interest: list[str] | None = None,
        depends_on: list[str] | None = None,
        tags: list[str] | None = None,
        review_by: str | None = None,
        polish_iters: int | None = None,
        smoke_cmd: str | None = None,
        kind: str = "code",
        content_spec: dict | None = None,
        goal_id: str | None = None,
        board_id: str = "default",
    ) -> Task:
        if priority not in schema.PRIORITIES:
            raise ValueError(f"unknown priority {priority!r}")
        if estimate is not None and estimate not in schema.ESTIMATES:
            raise ValueError(f"unknown estimate {estimate!r}")
        # Bots land in proposed; owner-created go straight to backlog.
        status = (
            schema.STATUS_BACKLOG if created_by == "owner"
            else schema.STATUS_PROPOSED
        )
        with self._lock:
            slug = self._next_task_slug()
            self._conn.execute(
                """
                INSERT INTO crew_tasks
                    (slug, title, body, status, project_slug, created_by,
                     priority, estimate, acceptance_criteria,
                     files_of_interest, depends_on, tags,
                     review_by, polish_iters, smoke_cmd, kind, content_spec,
                     goal_id, board_id)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    slug, title, body, status, project_slug, created_by,
                    priority, estimate,
                    json.dumps(acceptance_criteria or []),
                    json.dumps(files_of_interest or []),
                    json.dumps(depends_on or []),
                    json.dumps(tags or []),
                    review_by, polish_iters, smoke_cmd,
                    kind, json.dumps(content_spec or {}),
                    goal_id, board_id,
                ),
            )
            self._audit(
                slug, created_by, "create",
                detail=f"created in {status}",
                metadata={"title": title, "project": project_slug},
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def set_content_spec(self, slug: str, spec: dict) -> None:
        """Replace a content task's spec (request + result media ids)."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET content_spec = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (json.dumps(spec or {}), slug),
            )
            self._conn.commit()

    # ---------------------------------------------------------------- P6 goal_id

    def set_goal_id(self, slug: str, goal_id: str) -> None:
        """Stamp a task with the goal_id it belongs to (P6)."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET goal_id = ? WHERE slug = ?",
                (goal_id, slug),
            )
            self._conn.commit()

    def list_tasks_by_goal_id(self, goal_id: str) -> list["Task"]:
        """All tasks stamped with goal_id (subtasks + verify tickets)."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_tasks WHERE goal_id = ? ORDER BY id",
                (goal_id,),
            ).fetchall()
            return [self._row_to_task(r) for r in rows]

    def get_task(self, slug: str) -> Task | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM crew_tasks WHERE slug = ?", (slug,),
            ).fetchone()
            return self._row_to_task(row) if row else None

    def list_tasks(
        self, *,
        status: str | Iterable[str] | None = None,
        project_slug: str | None = None,
        assignee: str | None = None,
        board_id: str | None = None,
    ) -> list[Task]:
        clauses: list[str] = []
        params: list[Any] = []
        if status is not None:
            if isinstance(status, str):
                clauses.append("status = ?")
                params.append(status)
            else:
                statuses = list(status)
                if statuses:
                    clauses.append(
                        "status IN ("
                        + ",".join("?" * len(statuses)) + ")"
                    )
                    params.extend(statuses)
        if project_slug is not None:
            clauses.append("project_slug = ?")
            params.append(project_slug)
        if assignee is not None:
            clauses.append("assignee = ?")
            params.append(assignee)
        # P2 v-Next: when board_id is given, scope to that board only.
        # When None (back-compat default), return tasks from ALL boards.
        if board_id is not None:
            clauses.append("board_id = ?")
            params.append(board_id)
        sql = "SELECT * FROM crew_tasks"
        if clauses:
            sql += " WHERE " + " AND ".join(clauses)
        sql += " ORDER BY id"
        with self._lock:
            rows = self._conn.execute(sql, params).fetchall()
            return [self._row_to_task(r) for r in rows]

    def done_slugs(self) -> set[str]:
        """Set of done/archived task slugs. Lightweight (slug column only,
        no row hydration / JSON parse) — used by the dispatcher's per-tick
        depends_on check instead of materialising every done Task.
        Archived tasks are included so an archived upstream does not
        permanently block its dependents."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT slug FROM crew_tasks WHERE status IN (?, ?)",
                (schema.STATUS_DONE, schema.STATUS_ARCHIVED),
            ).fetchall()
            return {r["slug"] for r in rows}

    def archive_old_done(self, retention_days: float) -> int:
        """Auto-archive done tasks whose last update is older than
        retention_days. Returns the number archived. retention_days <= 0
        disables the sweep (returns 0). Keeps the Done column bounded.

        Single bulk UPDATE — done -> archived is the only legal transition out
        of done, so no per-row transition check is needed. Deliberately skips
        the per-task audit row a manual move writes: this is automated
        maintenance, not an operator action."""
        if retention_days <= 0:
            return 0
        cutoff_secs = int(retention_days * 86400)
        with self._lock:
            cur = self._conn.execute(
                "UPDATE crew_tasks SET status = ?, updated_at = datetime('now') "
                "WHERE status = ? AND updated_at < datetime('now', ?)",
                (schema.STATUS_ARCHIVED, schema.STATUS_DONE,
                 f"-{cutoff_secs} seconds"),
            )
            n = cur.rowcount
            self._conn.commit()
        return int(n or 0)

    def move_task(
        self, slug: str, to_status: str,
        *, actor: str = "owner", detail: str = "",
    ) -> Task:
        with self._lock:
            task = self.get_task(slug)
            if task is None:
                raise ValueError(f"unknown task {slug!r}")
            if to_status not in schema.ALL_STATUSES:
                raise ValueError(f"unknown status {to_status!r}")
            if to_status not in schema.ALLOWED_TRANSITIONS.get(task.status, frozenset()):
                raise ValueError(
                    f"transition {task.status!r} -> {to_status!r} not allowed"
                )
            self._conn.execute(
                "UPDATE crew_tasks SET status = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (to_status, slug),
            )
            self._audit(
                slug, actor, "move",
                detail=detail or f"{task.status} -> {to_status}",
                metadata={"from": task.status, "to": to_status},
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def assign_task(
        self, slug: str, assignee: str, *, actor: str = "owner",
    ) -> Task:
        if assignee not in schema.ASSIGNEES:
            raise ValueError(f"unknown assignee {assignee!r}")
        with self._lock:
            task = self.get_task(slug)
            if task is None:
                raise ValueError(f"unknown task {slug!r}")
            self._conn.execute(
                "UPDATE crew_tasks SET assignee = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (assignee, slug),
            )
            self._audit(
                slug, actor, "assign",
                detail=f"{task.assignee} -> {assignee}",
                metadata={"from": task.assignee, "to": assignee},
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def set_depends_on(
        self, slug: str, depends_on: list[str], *, actor: str = "owner",
    ) -> Task:
        """Manually set a task's blockers (#172). The dispatcher won't claim the
        task until every depends_on slug is done. Drops self-reference + blanks;
        rejects unknown slugs and direct cycles."""
        with self._lock:
            task = self.get_task(slug)
            if task is None:
                raise ValueError(f"unknown task {slug!r}")
            deps: list[str] = []
            for raw in depends_on:
                d = str(raw).strip()
                if not d or d == slug or d in deps:
                    continue
                dep_task = self.get_task(d)
                if dep_task is None:
                    raise ValueError(f"unknown blocker {d!r}")
                if slug in (dep_task.depends_on or []):
                    raise ValueError(f"cycle: {d} already depends on {slug}")
                deps.append(d)
            self._conn.execute(
                "UPDATE crew_tasks SET depends_on = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (json.dumps(deps), slug),
            )
            self._audit(
                slug, actor, "set_depends_on",
                detail=f"blocked-by {deps}", metadata={"depends_on": deps},
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def set_review_by(self, slug: str, reviewer: str | None) -> Task:
        """Set (or clear) the reviewer that the dispatcher's review loop
        keys on. A task promoted to `review` with review_by=None is skipped
        by the loop forever (that skip is intentional ONLY for owner-parked
        failures) — so the qa-pass promotion must set this, else verified
        work strands in review (observed: T-0307)."""
        with self._lock:
            task = self.get_task(slug)
            if task is None:
                raise ValueError(f"unknown task {slug!r}")
            self._conn.execute(
                "UPDATE crew_tasks SET review_by = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (reviewer, slug),
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def increment_attempt(self, slug: str) -> int:
        with self._lock:
            task = self.get_task(slug)
            if task is None:
                raise ValueError(f"unknown task {slug!r}")
            n = task.attempt_count + 1
            self._conn.execute(
                "UPDATE crew_tasks SET attempt_count = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (n, slug),
            )
            self._audit(
                slug, "system", "attempt",
                detail=f"attempt {n}",
                metadata={"attempt": n},
            )
            self._conn.commit()
            return n

    def heartbeat(self, slug: str) -> None:
        """Stamp heartbeat_at = now. A live runner calls this each turn
        so the reaper can tell it apart from a crash-orphan. Cheap
        single-column UPDATE, no audit row."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET heartbeat_at = datetime('now') "
                "WHERE slug = ?",
                (slug,),
            )
            self._conn.commit()

    def record_turn(self, slug: str, *, hive_tokens: int = 0,
                    action: str | None = None) -> None:
        """Per-turn bookkeeping in ONE write: bump heartbeat_at, add this
        turn's hive tokens, increment the turn count, and stamp the live
        `last_action` ("turn N · tool target") for board watching."""
        n = max(0, int(hive_tokens))
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET heartbeat_at = datetime('now'), "
                "hive_tokens = COALESCE(hive_tokens, 0) + ?, "
                "agent_turns = COALESCE(agent_turns, 0) + 1, "
                "last_action = COALESCE(?, last_action) WHERE slug = ?",
                (n, action, slug),
            )
            self._conn.commit()

    def set_last_action(self, slug: str, action: str) -> None:
        """Stamp the live current action (cheap single-column write, no
        turn-count change). Drives the board's live 'now doing' line."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET last_action = ? WHERE slug = ?",
                (action[:200], slug),
            )
            self._conn.commit()

    def append_thought(
        self, slug: str, turn: int, thought: str, action: str, cap: int = 12,
    ) -> None:
        """CP1: append one turn's reasoning to the task's live_thoughts buffer
        (kept to the last `cap` turns). Drives the in-ticket AI-thoughts panel."""
        with self._lock:
            row = self._conn.execute(
                "SELECT live_thoughts FROM crew_tasks WHERE slug = ?", (slug,),
            ).fetchone()
            buf: list = []
            if row and row[0]:
                try:
                    buf = json.loads(row[0])
                except Exception:  # noqa: BLE001
                    buf = []
            buf.append({
                "t": int(turn),
                "th": (thought or "")[:300],
                "a": (action or "")[:120],
            })
            buf = buf[-cap:]
            self._conn.execute(
                "UPDATE crew_tasks SET live_thoughts = ? WHERE slug = ?",
                (json.dumps(buf), slug),
            )
            self._conn.commit()

    def set_plan_spec(self, slug: str, spec: dict) -> None:
        """CP2: store the master-plan spec on a kind='plan' ticket."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET plan_spec = ? WHERE slug = ?",
                (json.dumps(spec or {}), slug),
            )
            self._conn.commit()

    def set_steer(self, slug: str, msg: str) -> None:
        """CP1: queue an owner steer nudge for a running task (capped)."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET steer_message = ? WHERE slug = ?",
                ((msg or "").strip()[:1000], slug),
            )
            self._conn.commit()

    def pop_steer(self, slug: str) -> str | None:
        """CP1: read + clear the pending steer nudge (the loop injects it once)."""
        with self._lock:
            row = self._conn.execute(
                "SELECT steer_message FROM crew_tasks WHERE slug = ?", (slug,),
            ).fetchone()
            msg = row[0] if row and row[0] else None
            if msg:
                self._conn.execute(
                    "UPDATE crew_tasks SET steer_message = NULL WHERE slug = ?",
                    (slug,),
                )
                self._conn.commit()
            return msg

    def set_task_summary(self, slug: str, summary: str, by: str = "") -> None:
        """#198: store the last-agent handoff summary for a task — a short
        "what I did + current state + next step". Overwrites any prior summary
        and stamps the author (model/agent name) + time, so the board can show
        "last touched by X". Truncated to keep the row small; no-op on empty."""
        text = (summary or "").strip()[:1200]
        if not text:
            return
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET last_summary = ?, last_summary_by = ?, "
                "last_summary_at = datetime('now') WHERE slug = ?",
                (text, (by or "")[:80], slug),
            )
            self._conn.commit()

    def bump_parse_fail(self, slug: str) -> None:
        """Increment a task's parse-fail counter (one unparseable agent
        reply). Read in aggregate by the stats endpoint."""
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET parse_fails = COALESCE(parse_fails, 0) + 1 "
                "WHERE slug = ?",
                (slug,),
            )
            self._conn.commit()

    def parse_fail_totals(self) -> tuple[int, int]:
        """(total_parse_fails, total_agent_turns) across all tasks — the
        cheap source for the stats parse-fail rate (replaces the
        transcript scan)."""
        with self._lock:
            row = self._conn.execute(
                "SELECT COALESCE(SUM(parse_fails),0) AS f, "
                "COALESCE(SUM(agent_turns),0) AS t FROM crew_tasks"
            ).fetchone()
            return (int(row["f"]), int(row["t"])) if row else (0, 0)

    def add_tokens(self, slug: str, *, kind: str, n: int) -> None:
        """Accumulate token usage on a task. kind must be 'hive' or
        'claude' — the two are tracked in separate columns and NEVER
        combined."""
        if kind not in ("hive", "claude"):
            raise ValueError(f"token kind must be hive|claude, got {kind!r}")
        if n <= 0:
            return
        col = "hive_tokens" if kind == "hive" else "claude_tokens"
        with self._lock:
            self._conn.execute(
                f"UPDATE crew_tasks SET {col} = COALESCE({col}, 0) + ? "
                "WHERE slug = ?",
                (int(n), slug),
            )
            self._conn.commit()

    def tokens_by_day(self, days: int = 30) -> list[dict]:
        """Aggregate token usage per calendar day for the last *days* days.

        Groups ``crew_tasks`` rows by ``date(updated_at)`` — the date the
        task last accumulated tokens (best available per-day proxy; tokens
        accrue via ``record_turn`` / ``add_tokens``, which both touch
        ``updated_at`` via the task path).  Returns a list of dicts::

            [{"date": "YYYY-MM-DD", "hive": int, "claude": int, "total": int}, ...]

        Ascending by date, always exactly *days* entries, zero-filled for
        days with no recorded activity so the line chart never has gaps.
        Only the last *days* calendar days (today inclusive, UTC) are
        considered — older data is dropped to keep the response tight.
        """
        days = max(1, int(days))
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT
                    date(updated_at) AS day,
                    COALESCE(SUM(hive_tokens),   0) AS hive,
                    COALESCE(SUM(claude_tokens), 0) AS claude
                FROM crew_tasks
                WHERE updated_at >= date('now', ? || ' days')
                GROUP BY day
                ORDER BY day ASC
                """,
                (f"-{days - 1}",),
            ).fetchall()

        # Build a lookup so we can zero-fill missing days.
        by_day: dict[str, dict] = {
            r["day"]: {"hive": int(r["hive"]), "claude": int(r["claude"])}
            for r in rows
        }

        import datetime as _dt
        today = _dt.date.today()
        result: list[dict] = []
        for i in range(days - 1, -1, -1):
            d = today - _dt.timedelta(days=i)
            key = d.isoformat()
            entry = by_day.get(key, {"hive": 0, "claude": 0})
            result.append({
                "date":   key,
                "hive":   entry["hive"],
                "claude": entry["claude"],
                "total":  entry["hive"] + entry["claude"],
            })
        return result

    def rolling_24h_claude_cost_usd(
        self, *, usd_per_million_tokens: float = 6.0,
    ) -> float:
        """Return estimated USD spent on claude escalations in the last 24 hours.

        Sums claude_tokens across all tasks whose updated_at falls within the
        last 24 hours and converts using the same blended rate used by the
        /board/stats endpoint ($6 / 1M tokens by default).

        The 24-hour window uses SQLite's datetime('now', '-24 hours') so it is
        always relative to the current UTC wall clock — no timezone conversion
        needed.
        """
        with self._lock:
            row = self._conn.execute(
                """
                SELECT COALESCE(SUM(claude_tokens), 0) AS total
                FROM crew_tasks
                WHERE updated_at >= datetime('now', '-24 hours')
                """,
            ).fetchone()
            total_tokens = int(row["total"]) if row else 0
        return total_tokens / 1_000_000 * usd_per_million_tokens

    def add_lesson(
        self, project_slug: str, body: str, *,
        task_slug: str = "", tags: list[str] | None = None,
    ) -> Lesson:
        """Persist a distilled lesson note for a project. Seeded into
        future task briefs so the next attempt avoids the same mistake."""
        body = (body or "").strip()
        if not body:
            raise ValueError("lesson body must not be empty")
        with self._lock:
            self._conn.execute(
                "INSERT INTO crew_lessons (project_slug, task_slug, tags, body) "
                "VALUES (?, ?, ?, ?)",
                (project_slug, task_slug, json.dumps(tags or []), body),
            )
            self._conn.commit()
        return Lesson(
            project_slug=project_slug, body=body,
            task_slug=task_slug, tags=tags or [],
        )

    def recent_lessons(
        self, project_slug: str, *, limit: int = 3,
    ) -> list[Lesson]:
        """Most-recent lessons for a project, newest first."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_lessons WHERE project_slug = ? "
                "ORDER BY id DESC LIMIT ?",
                (project_slug, int(limit)),
            ).fetchall()
        return [
            Lesson(
                project_slug=r["project_slug"], body=r["body"],
                task_slug=r["task_slug"],
                tags=json.loads(r["tags"] or "[]"),
                created_at=r["created_at"],
            )
            for r in rows
        ]

    def relevant_lessons(
        self,
        project_slug: str,
        task_title: str,
        task_body: str,
        *,
        limit: int = 3,
    ) -> list[Lesson]:
        """Return up to *limit* lessons for a project ranked by keyword
        overlap with *task_title* + *task_body*, with recency as a
        tiebreaker.  Mirrors the ``_relevant_skills`` scorer in
        ``hive_agent_loop.py``: extract 4+-character words from the task
        text and count how many appear in each lesson body.  Lessons with
        no overlap are still eligible so a project with few lessons
        doesn't produce an empty result."""
        import re as _re

        # Fetch all lessons for the project (newest first so recency wins
        # ties with equal score).
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_lessons WHERE project_slug = ? "
                "ORDER BY id DESC",
                (project_slug,),
            ).fetchall()
        if not rows:
            return []

        lessons = [
            Lesson(
                project_slug=r["project_slug"], body=r["body"],
                task_slug=r["task_slug"],
                tags=json.loads(r["tags"] or "[]"),
                created_at=r["created_at"],
            )
            for r in rows
        ]

        # Build the keyword set from the task text (same regex as
        # _relevant_skills: 4+ lowercase alpha characters).
        query_words = set(
            _re.findall(r"[a-z]{4,}", (task_title + " " + task_body).lower())
        )

        def _score(lesson: Lesson) -> int:
            hay = lesson.body.lower()
            return sum(1 for w in query_words if w in hay)

        # Sort descending by score; within the same score the earlier
        # position (higher id = newer = lower index in `lessons`) is
        # preserved because Python's sort is stable.
        ranked = sorted(lessons, key=_score, reverse=True)
        return ranked[:limit]

    # ---------------------------------------------------------------- boards (P2)

    def _row_to_board(self, row: sqlite3.Row) -> Board:
        return Board(
            board_id=row["board_id"],
            name=row["name"],
            description=row["description"],
            created_at=row["created_at"],
        )

    def ensure_default_board(self) -> None:
        """Idempotently ensure the 'default' board exists (called by schema.apply)."""
        with self._lock:
            self._conn.execute(
                "INSERT OR IGNORE INTO crew_boards (board_id, name, description) "
                "VALUES ('default', 'Default', 'Default board')"
            )
            self._conn.commit()

    def create_board(
        self, board_id: str, name: str, description: str = "",
    ) -> Board:
        """Create a new board. Raises ValueError if board_id already exists."""
        with self._lock:
            existing = self._conn.execute(
                "SELECT board_id FROM crew_boards WHERE board_id = ?",
                (board_id,),
            ).fetchone()
            if existing:
                raise ValueError(f"board {board_id!r} already exists")
            self._conn.execute(
                "INSERT INTO crew_boards (board_id, name, description) "
                "VALUES (?, ?, ?)",
                (board_id, name, description),
            )
            self._conn.commit()
            return self.get_board(board_id)  # type: ignore[return-value]

    def get_board(self, board_id: str) -> Board | None:
        with self._lock:
            row = self._conn.execute(
                "SELECT * FROM crew_boards WHERE board_id = ?",
                (board_id,),
            ).fetchone()
            return self._row_to_board(row) if row else None

    def list_boards(self) -> list[Board]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_boards ORDER BY created_at"
            ).fetchall()
            return [self._row_to_board(r) for r in rows]

    # ---------------------------------------------------------------- meta (kv)

    def get_meta(self, key: str, default: str | None = None) -> str | None:
        """Read a value from crew_meta by key. Returns *default* if absent."""
        with self._lock:
            row = self._conn.execute(
                "SELECT value FROM crew_meta WHERE key = ?", (key,)
            ).fetchone()
            return str(row["value"]) if row else default

    def list_meta_like(self, pattern: str) -> list[tuple[str, str]]:
        """Return all (key, value) pairs from crew_meta where key LIKE *pattern*."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT key, value FROM crew_meta WHERE key LIKE ?", (pattern,)
            ).fetchall()
            return [(str(r["key"]), str(r["value"])) for r in rows]

    def set_meta(self, key: str, value: str) -> None:
        """UPSERT a key/value pair into crew_meta. Persisted on disk."""
        with self._lock:
            self._conn.execute(
                "INSERT INTO crew_meta (key, value) VALUES (?, ?) "
                "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
                (key, value),
            )
            self._conn.commit()

    def is_paused(self) -> bool:
        """True when the board dispatcher is paused (board.paused == '1')."""
        return self.get_meta("board.paused", "0") == "1"

    def set_paused(self, paused: bool) -> None:
        """Persist the pause state. Survives gateway restart."""
        self.set_meta("board.paused", "1" if paused else "0")

    def count_lessons(self, project_slug: str | None = None) -> int:
        """Total lesson count, optionally scoped to a project."""
        with self._lock:
            if project_slug:
                row = self._conn.execute(
                    "SELECT COUNT(*) AS n FROM crew_lessons WHERE project_slug = ?",
                    (project_slug,),
                ).fetchone()
            else:
                row = self._conn.execute(
                    "SELECT COUNT(*) AS n FROM crew_lessons"
                ).fetchone()
            return int(row["n"]) if row else 0

    def update_verify_results(
        self, slug: str, results: dict, *, actor: str = "system",
    ) -> Task:
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET verify_results = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (json.dumps(results), slug),
            )
            self._audit(
                slug, actor, "verify",
                detail="updated verify_results",
                metadata=results,
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def add_comment(
        self, slug: str, actor: str, comment: str,
    ) -> AuditEntry:
        with self._lock:
            self._audit(slug, actor, "comment", detail=comment)
            self._conn.commit()
            rows = self._conn.execute(
                "SELECT * FROM crew_audit WHERE task_slug = ? "
                "ORDER BY id DESC LIMIT 1",
                (slug,),
            ).fetchall()
            return self._row_to_audit(rows[0])

    def update_acceptance_criteria(
        self, slug: str, criteria: list[dict],
        *, actor: str = "owner",
    ) -> Task:
        with self._lock:
            self._conn.execute(
                "UPDATE crew_tasks SET acceptance_criteria = ?, "
                "updated_at = datetime('now') WHERE slug = ?",
                (json.dumps(criteria), slug),
            )
            self._audit(
                slug, actor, "update_criteria",
                detail=f"{sum(1 for c in criteria if c.get('checked'))}/"
                       f"{len(criteria)} checked",
            )
            self._conn.commit()
            return self.get_task(slug)  # type: ignore[return-value]

    def delete_task(self, slug: str) -> bool:
        """Hard-delete a task and all its child rows from the database.

        Removes the task from ``crew_tasks`` plus every related row keyed
        by slug: ``crew_audit`` entries, ``crew_approvals`` entries, and
        any lesson notes that reference this task in ``crew_lessons``.
        All deletes happen inside a single transaction so the DB is never
        left in a partial state.

        Returns True when a task row was found and deleted, False when the
        slug did not exist (so callers can return 404 cleanly).
        """
        with self._lock:
            row = self._conn.execute(
                "SELECT slug FROM crew_tasks WHERE slug = ?", (slug,),
            ).fetchone()
            if row is None:
                return False
            # Delete child rows first (no FK constraints, but cleaner).
            self._conn.execute(
                "DELETE FROM crew_audit WHERE task_slug = ?", (slug,),
            )
            self._conn.execute(
                "DELETE FROM crew_approvals WHERE task_slug = ?", (slug,),
            )
            # crew_lessons are keyed by project, but task_slug is stored
            # as a convenience field — remove the lesson notes that belong
            # to this task so no orphan detail remains.
            self._conn.execute(
                "DELETE FROM crew_lessons WHERE task_slug = ?", (slug,),
            )
            self._conn.execute(
                "DELETE FROM crew_tasks WHERE slug = ?", (slug,),
            )
            self._conn.commit()
            return True

    def audit_for(self, slug: str) -> list[AuditEntry]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_audit WHERE task_slug = ? ORDER BY id",
                (slug,),
            ).fetchall()
            return [self._row_to_audit(r) for r in rows]

    # ---------------------------------------------------------------- approvals

    def request_approval(
        self, *, task_slug: str, requested_by: str,
        kind: str, summary: str, payload: dict | None = None,
    ) -> int:
        with self._lock:
            cur = self._conn.execute(
                """
                INSERT INTO crew_approvals
                    (task_slug, requested_by, kind, summary, payload)
                VALUES (?, ?, ?, ?, ?)
                """,
                (
                    task_slug, requested_by, kind, summary,
                    json.dumps(payload or {}),
                ),
            )
            self._audit(
                task_slug, requested_by, "approval_request",
                detail=f"{kind}: {summary}",
            )
            self._conn.commit()
            return int(cur.lastrowid or 0)

    def resolve_approval(
        self, approval_id: int, *, approved: bool, actor: str = "owner",
    ) -> None:
        with self._lock:
            row = self._conn.execute(
                "SELECT task_slug, kind FROM crew_approvals WHERE id = ?",
                (approval_id,),
            ).fetchone()
            if row is None:
                raise ValueError(f"unknown approval {approval_id}")
            new_status = "approved" if approved else "denied"
            self._conn.execute(
                "UPDATE crew_approvals SET status = ?, "
                "resolved_at = datetime('now') WHERE id = ?",
                (new_status, approval_id),
            )
            self._audit(
                row["task_slug"], actor, "approval_resolve",
                detail=f"{row['kind']}: {new_status}",
                metadata={"approval_id": approval_id, "approved": approved},
            )
            self._conn.commit()

    def list_pending_approvals(self) -> list[dict]:
        with self._lock:
            rows = self._conn.execute(
                "SELECT * FROM crew_approvals WHERE status = 'pending' "
                "ORDER BY id"
            ).fetchall()
        out: list[dict] = []
        for r in rows:
            out.append({
                "id": r["id"],
                "task_slug": r["task_slug"],
                "requested_by": r["requested_by"],
                "kind": r["kind"],
                "summary": r["summary"],
                "payload": json.loads(r["payload"]),
                "created_at": r["created_at"],
            })
        return out
